/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
 */
export class Garnishment extends SpeakeasyBase {
    /**
     * Whether or not this garnishment is currently active.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "active" })
    active?: boolean;

    /**
     * The amount of the garnishment. Either a percentage or a fixed dollar amount. Represented as a float, e.g. "8.00".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: string;

    /**
     * The maximum deduction per annum. A null value indicates no maximum. Represented as a float, e.g. "200.00".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "annual_maximum" })
    annualMaximum?: string;

    /**
     * Whether the garnishment is court ordered.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "court_ordered" })
    courtOrdered?: boolean;

    /**
     * Whether the amount should be treated as a percentage to be deducted per pay period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deduct_as_percentage" })
    deductAsPercentage?: boolean;

    /**
     * The description of the garnishment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The UUID of the employee to which this garnishment belongs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee_uuid" })
    employeeUuid?: number;

    /**
     * The maximum deduction per pay period. A null value indicates no maximum. Represented as a float, e.g. "16.00".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pay_period_maximum" })
    payPeriodMaximum?: string;

    /**
     * Whether the garnishment should recur indefinitely.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recurring" })
    recurring?: boolean;

    /**
     * The number of times to apply the garnishment. Ignored if recurring is true.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "times" })
    times?: number;

    /**
     * The UUID of the garnishment in Gusto.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "uuid" })
    uuid?: string;

    /**
     * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
