/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Example response
 */
export class Industry extends SpeakeasyBase {
    /**
     * Company uuid
     */
    @SpeakeasyMetadata()
    @Expose({ name: "company_uuid" })
    companyUuid?: string;

    /**
     * North American Industry Classification System (NAICS) is used to classify businesses with a six digit number based on the primary type of work the business performs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "naics_code" })
    naicsCode?: string;

    /**
     * A list of Standard Industrial Classification (SIC) codes, which are four digit number that categorize the industries that companies belong to based on their business activities.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sic_codes" })
    sicCodes?: string[];

    /**
     * Industry title
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}
