/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class PayrollBlockersErrorErrorsMetadata extends SpeakeasyBase {
  /**
   * A categorization of the payroll blocker, e.g. "geocode_error"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "key" })
  key?: string;
}

export class PayrollBlockersErrorErrors extends SpeakeasyBase {
  /**
   * The string "payroll_blocker"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "category" })
  category?: string;

  /**
   * The string "base"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "error_key" })
  errorKey?: string;

  /**
   * Human readable description of the payroll blocker
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => PayrollBlockersErrorErrorsMetadata)
  metadata?: PayrollBlockersErrorErrorsMetadata;
}

/**
 * Payroll Blockers Error
 *
 * @remarks
 *
 * For detailed information, see the [Payroll Blockers guide](https://docs.gusto.com/embedded-payroll/docs/payroll-blockers)
 */
export class PayrollBlockersError extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: PayrollBlockersErrorErrors })
  @Expose({ name: "errors" })
  @Type(() => PayrollBlockersErrorErrors)
  errors?: PayrollBlockersErrorErrors[];
}
