/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PostEmployeeYtdBenefitAmountsFromDifferentCompany extends SpeakeasyBase {
    /**
     * The benefit type supported by Gusto.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "benefit_type" })
    benefitType?: number;

    /**
     * The tax year for which this amount applies.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_year" })
    taxYear: number;

    /**
     * The year-to-date company contribution made outside the current company.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ytd_company_contribution_amount" })
    ytdCompanyContributionAmount: string;

    /**
     * The year-to-date employee deduction made outside the current company.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ytd_employee_deduction_amount" })
    ytdEmployeeDeductionAmount: string;
}
