/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UnprocessableEntityErrorObjectErrors extends SpeakeasyBase {
  /**
   * Specifies the type of error. The category provides error groupings and can be used to build custom error handling in your integration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "category" })
  category?: string;

  /**
   * Specifies where the error occurs. Typically this key identifies the attribute/parameter related to the error.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "error_key" })
  errorKey?: string;

  /**
   * Provides details about the error - generally this message can be surfaced to an end user.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Contains relevant data to identify the resource in question when applicable. For example, to identify an entity `entity_type` and `entity_uuid` will be provided.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  metadata?: Record<string, any>;
}

/**
 * Unprocessable Entity
 *
 * @remarks
 *
 * This may happen when the body of your request contains errors such as `invalid_attribute_value`, or the request fails due to an `invalid_operation`. See the [Errors Categories](https://docs.gusto.com/embedded-payroll/docs/error-categories) guide for more details.
 *
 */
export class UnprocessableEntityErrorObject extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: UnprocessableEntityErrorObjectErrors })
  @Expose({ name: "errors" })
  @Type(() => UnprocessableEntityErrorObjectErrors)
  errors?: UnprocessableEntityErrorObjectErrors[];
}
