/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The representation of an unprocessed termination pay period.
 */
export class UnprocessedTerminationPayPeriod extends SpeakeasyBase {
    /**
     * The check date of the pay period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "check_date" })
    checkDate?: string;

    /**
     * The debit date of the pay period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "debit_date" })
    debitDate?: string;

    /**
     * The full name of the employee.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee_name" })
    employeeName?: string;

    /**
     * A unique identifier of the employee.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "employee_uuid" })
    employeeUuid?: string;

    /**
     * The end date of the pay period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    endDate?: string;

    /**
     * A unique identifier of the pay schedule to which the pay period belongs.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pay_schedule_uuid" })
    payScheduleUuid?: string;

    /**
     * The start date of the pay period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    startDate?: string;
}
