/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeleteV1CompanyBenefitsCompanyBenefitIdRequest extends SpeakeasyBase {
    /**
     * The UUID of the company benefit
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company_benefit_id" })
    companyBenefitId: string;
}

export class Base extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "full_message" })
    fullMessage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}

export class Errors extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Base })
    @Expose({ name: "base" })
    @Type(() => Base)
    base?: Base[];
}

/**
 * Unprocessable Entity
 */
export class DeleteV1CompanyBenefitsCompanyBenefitIdResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    @Type(() => Errors)
    errors?: Errors;
}

export class DeleteV1CompanyBenefitsCompanyBenefitIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Unprocessable Entity
     */
    @SpeakeasyMetadata()
    object?: DeleteV1CompanyBenefitsCompanyBenefitIdResponseBody;
}
