/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class GetV1CompaniesCompanyUuidTaxRequirementsRequest extends SpeakeasyBase {
    /**
     * The UUID of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company_uuid" })
    companyUuid: string;
}

export class GetV1CompaniesCompanyUuidTaxRequirementsResponseBody extends SpeakeasyBase {
    /**
     * If all requirements for the state have been satisfied such that the company can complete
     *
     * @remarks
     * onboarding, the company is `setup_complete` in the state. A company must be `setup_complete` in
     * all relevant states to complete the `state_setup` company onboarding step.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "setup_complete" })
    setupComplete?: boolean;

    /**
     * One of the two-letter state abbreviations for the fifty United States and the District of Columbia (DC)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "state" })
    state?: string;
}

export class GetV1CompaniesCompanyUuidTaxRequirementsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata({ elemType: GetV1CompaniesCompanyUuidTaxRequirementsResponseBody })
    classes?: GetV1CompaniesCompanyUuidTaxRequirementsResponseBody[];
}
