/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetV1WebhookSubscriptionVerificationTokenUuidRequest extends SpeakeasyBase {
    /**
     * The webhook subscription UUID.
     */
    @SpeakeasyMetadata({
        data: "pathParam, style=simple;explode=false;name=webhook_subscription_uuid",
    })
    webhookSubscriptionUuid: string;
}

export class GetV1WebhookSubscriptionVerificationTokenUuidResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
