/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetV1BenefitsBenefitIdRequest extends SpeakeasyBase {
    /**
     * The benefit type in Gusto.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=benefit_id" })
    benefitId: string;
}

export class GetV1BenefitsBenefitIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Supported benefit response
     */
    @SpeakeasyMetadata()
    supportedBenefit?: shared.SupportedBenefit;
}
