/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetV1BenefitsCompanyBenefitIdSummaryRequest extends SpeakeasyBase {
    /**
     * The UUID of the company benefit
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company_benefit_id" })
    companyBenefitId: string;

    /**
     * Display employee payroll item summary
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=detailed" })
    detailed?: boolean;

    /**
     * The end date for which to retrieve company benefit summary
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=end_date" })
    endDate?: string;

    /**
     * The start date for which to retrieve company benefit summary
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=start_date" })
    startDate?: string;
}

export class GetV1BenefitsCompanyBenefitIdSummaryResponse extends SpeakeasyBase {
    /**
     * Benefit summary response
     */
    @SpeakeasyMetadata()
    benefitSummary?: shared.BenefitSummary;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
