/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class PutV1CompaniesCompanyIdPayrollsPayrollIdCalculateRequest extends SpeakeasyBase {
    /**
     * The UUID of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company_id" })
    companyId: string;

    /**
     * The UUID of the payroll
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=payroll_id" })
    payrollId: string;
}

export class PutV1CompaniesCompanyIdPayrollsPayrollIdCalculateResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Unprocessable Entity
     */
    @SpeakeasyMetadata()
    putV1CompaniesCompanyIdPayrollsPayrollIdCalculate422ApplicationJSONOneOf?: any;
}
